const users = [
    {
        id: 1,
        name: 'Gilberto Panquian',
        userName: 'panquiang',
        email: 'gilberto.panquian@gmail.com',
        password: '123456',
    },
];

const productType = [
    {
        id: 1,
        name: 'Vinil',
        code: 'vin001',
        description: 'Vinilos',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 2,
        name: 'Papel',
        code: 'ppl002',
        description: 'hojas de diferentes tipos imprimibles y otro tipo',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 3,
        name: 'Cartulina',
        code: 'car003',
        description: 'Cartulina de diferentes tipos y colores',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 4,
        name: 'Herramientas Cricut',
        code: 'her004',
        description: 'Herramientas para el uso de la Cricut',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 5,
        name: 'Equipos',
        code: 'equ005',
        description: 'Equipos para diferentes tipos de trabajo',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 6,
        name: 'Consumibles',
        code: 'con006',
        description: 'Consumibles de los equipos',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
];

const equip = [
    {
        id: 1,
        name: 'Cricut Maker 3',
        code: 'cctmkr3',
        categoryType: 5,
        size: 1,
        units: 1,
        description: 'Cricut Maker 3, plotter de corte',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 2,
        name: 'Impresora Epson L4150',
        code: 'EL4150',
        categoryType: 5,
        size: 1,
        units: 1,
        description: 'Impresora de Inyección de Tinta',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 3,
        name: 'Vinilo Azul',
        code: 'vinazl',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible azul',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 4,
        name: 'Vinilo Rojo',
        code: 'vinrjo',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible rojo',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 5,
        name: 'Vinilo Negro',
        code: 'vinnro',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible negro',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 6,
        name: 'Vinilo Blanco',
        code: 'vinbco',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible blanco',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 7,
        name: 'Vinilo Verde Oscuro',
        code: 'vinvro',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible verder oscuro',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 8,
        name: 'Vinilo Verde Claro',
        code: 'vinvco',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible verde claro',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 9,
        name: 'Vinilo Dorado',
        code: 'vindro',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible dorado',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 10,
        name: 'Vinilo Plata',
        code: 'vinpta',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible plata',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 11,
        name: 'Vinilo Lila',
        code: 'vinlla',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible Lila',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 12,
        name: 'Vinilo Morado',
        code: 'vinmdo',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible morado',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 13,
        name: 'Vinilo Naranja',
        code: 'vinnja',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo removible naranja',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 14,
        name: 'Vinilo Sublimado Negro',
        code: 'vinsno',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo Sublimado Negro',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 15,
        name: 'Vinilo Sublimado Rojo',
        code: 'vinsro',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo sublimado rojo',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 16,
        name: 'Vinilo Sublimado Naranja',
        code: 'vinsna',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Vinilo sublimado naranja',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 17,
        name: 'Papel transfer',
        code: 'pplter',
        categoryType: 1,
        size: 1,
        units: 1,
        description: 'Papael transfer para colocar vinilo',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
    {
        id: 17,
        name: 'Hojas Blancas',
        code: 'hojbas',
        categoryType: 1,
        size: 95,
        units: 100,
        description: 'Papael transfer para colocar vinilo',
        dateAdded: '2024-03-03',
        dateLastUpdate: '2024-03-03',
    },
];